[package]
name = "tqdm"
version = "0.1.0"
edition = "2018"

repository = "https://github.com/mrlazy1708/tqdm"
license = "MIT OR Apache-2.0"
keywords = ["tqdm", "progress", "iterator"]
categories = ["accessibility", "command-line-utilities"]

[dependencies]
termion = "1.5.6"
