[package]
name = "tqdm"
version = "0.3.0"
edition = "2018"
readme = "README.md"

license = "MIT OR Apache-2.0"
description = "Python tqdm in Rust"
repository = "https://github.com/mrlazy1708/tqdm"
documentation = "https://docs.rs/tqdm/latest/tqdm"

authors = ["yihengdu"]
keywords = ["tqdm", "progress", "iterator"]
categories = ["accessibility", "command-line-utilities"]

[dependencies]
lazy_static = "1.4.0"
termion = "1.5.6"
